# Generated by Django 3.0.1 on 2021-03-29 19:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appblog')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appblog.Kategoria')),
            ],
            options={
                'verbose_name_plural': 'categorías',
                'ordering': ['-created'],
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen')),
                ('imagefront', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagenfront')),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('cursiva', models.TextField(blank=True, max_length=600, null=True, verbose_name='Cursiva')),
                ('narrativa', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Narrativa')),
                ('blocquote', models.TextField(blank=True, max_length=300, null=True, verbose_name='Blocquote')),
                ('titleone', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-uno')),
                ('imageone', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen-uno')),
                ('subtitleone', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-uno')),
                ('subtitleuno', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-uno-uno')),
                ('contenone', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-uno')),
                ('imagetwo', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen-dos')),
                ('titletwo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-dos')),
                ('subtitletwo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-dos')),
                ('contentwo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-dos')),
                ('imagethree', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen-tres')),
                ('titlethree', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-tres')),
                ('subtitlethree', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-tres')),
                ('contenthree', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-tres')),
                ('imagefour', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen-cuatro')),
                ('titlefour', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-cuatro')),
                ('subtitlefour', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-cuatro')),
                ('contenfour', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-cuatro')),
                ('imagefive', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagen-cinco')),
                ('titlefive', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-cinco')),
                ('subtitlefive', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitulo-cinco')),
                ('contenfive', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-cinco')),
                ('titleultimo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Titulo-ultimo')),
                ('contentultimo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido-ultimo')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('imageauthor', models.ImageField(blank=True, null=True, upload_to='appblog', verbose_name='Imagenautor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('kategoria', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='appblog.Kategoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appblog.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appblog.Post')),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
            },
        ),
    ]
