# Generated by Django 3.0.1 on 2021-05-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1900, null=True, verbose_name='Descripción'),
        ),
    ]
